### api test
GET http://localhost:8000


# APIs

### post new user
POST  http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fName": "Prem",
    "lName": "Acharya",
    "email": "a@a.com",
    "password": "123456"
}


### post new user
POST  http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "123456"
}


# =========== transaction apis
### post new transaction
POST  http://localhost:8000/api/v1/transaction
Content-Type: application/json

{
    "userId": "62d89c980b44932b9a9919ca",
    "type": "expenses",
    "title": "studying",
    "amount": 100

}


### get all trasaction for the specific user based on thir id
GET http://localhost:8000/api/v1/transaction
Authorization: 62d89c980b44932b9a9919ca